#!/usr/bin/env python

import os

curr_file = os.path.abspath(__file__)
if not curr_file.endswith('/set_paths'):
  raise Exception('Unexpected error occurred; wrong file called')

last_char_length = len('/set_paths')
base_path = curr_file[:-last_char_length]
data_path = '%s/problem_data' % base_path

py_path = '%s/python_code/path.py' % base_path
py_contents = "DATA_PATH = '%s'\n" % data_path
with open(py_path, 'w') as fh:
  fh.write(py_contents)

js_path = '%s/js/path.js' % base_path
js_contents = "exports.DATA_PATH = '%s';\n" % data_path
with open(js_path, 'w') as fh:
  fh.write(js_contents)

export_stmt = ['\n',
               '# dhermes-project-euler adding to PYTHONPATH for imports\n',
               'export PYTHONPATH=$PYTHONPATH:%s\n' % base_path,
               '# dhermes-project-euler finished adding to PYTHONPATH\n']
bash_profile = os.path.join(os.path.expanduser('~'), '.bash_profile')
with open(bash_profile, 'a') as fh:
  fh.write(''.join(export_stmt))
