#!/usr/bin/env python

# Find the difference between the sum of the 
# squares of the first one hundred natural 
# numbers and the square of the sum.

from python_code.decorators import euler_timer

def sum_first_n(n):
    return n*(n + 1)/2

def sum_first_n_sq(n):
    return n*(n + 1)*(2*n + 1)/6

@euler_timer(6)
def main():
    print abs(sum_first_n_sq(100) - sum_first_n(100)**2)

if __name__ == "__main__":
    main()
