#!/usr/bin/env python

# Find the greatest product of five consecutive
# digits in the 1000-digit number.

from python_code.decorators import euler_timer
from python_code.functions import get_data

def greatest_product_digits(number, digits):
    n = [ int(xx) for xx in str(number)]
    prods = [ reduce(lambda x,y : x*y, n[i:i + digits]) for i in range(len(n) - digits + 1) ]
    return max(prods)

@euler_timer(8)
def main():
    n = get_data(8)
    n = n.split("\n")
    n = [ line.strip() for line in n ]
    n = int("".join(n))

    print greatest_product_digits(n, 5)

if __name__ == "__main__":
    main()
