#!/usr/bin/env python

# Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

from python_code.decorators import euler_timer
from python_code.functions import get_data

@euler_timer(13)
def main():
    number = get_data(13)
    numbers = [int(line) for line in number.split("\n") if line]
    total = sum(numbers)
    first_digits = int(str(total)[:10])
    print first_digits

if __name__ == "__main__":
    main()
