#!/usr/bin/env python

# Find the sum of all the primes below two million.

from python_code.decorators import euler_timer

def sieve(n):
    to_check = [1] * (n+1)
    for i in range(2,n+1):
        if to_check[i]:
            for j in range(2*i,n+1,i):
                to_check[j] = 0

    return [ i for i in range(2,n+1) if to_check[i] ]

@euler_timer(10)
def main():
    print sum(sieve(2000000-1))

if __name__ == "__main__":
    main()
