#!/usr/bin/env python

# Starting in the top left corner of a 2 x 2 grid, there are 6 routes (without backtracking) to the bottom right corner.
# How many routes are there through a 20 x 20 grid?

from python_code.decorators import euler_timer

def factorial_helper(n, prod):
    if n < 2:
        return prod
    else:
        return factorial_helper(n - 1, n*prod)

def factorial(n):
    return factorial_helper(n, 1)

# In an n x m grid there are (n + m) C m = (n + m) C n such paths.
def num_paths(n, m):
    return factorial(n + m)/(factorial(n)*factorial(m))

@euler_timer(15)
def main():
    print num_paths(20, 20)

if __name__ == "__main__":
    main()
