#!/usr/bin/env python

# What is the first term in the Fibonacci sequence to contain 1000 digits?

from python_code.decorators import euler_timer
from python_code.functions import fibonacci_generator

@euler_timer(25)
def main():
    fib = fibonacci_generator()
    fib_index = 0
    for value in fib:
        # number of digits
        if len(str(value)) < 1000:
            fib_index += 1
            continue
        else:
            print fib_index
            break

if __name__ == "__main__":
    main()
