#!/usr/bin/env python

import operator

from python_code.decorators import euler_timer
from python_code.functions import apply_to_list

@euler_timer(29)
def main():
    n = 100
    powers = apply_to_list(operator.pow, range(2, n + 1))
    print len(set(powers))

if __name__ == "__main__":
    main()
