#!/usr/bin/env python

from python_code.decorators import euler_timer

@euler_timer(29)
def main():
    n = 100
    print len(set([ a**b for a in range(2, n + 1)
                    for b in range(2, n + 1) ]))

if __name__ == "__main__":
    main()
