#!/usr/bin/env python

# Find the sum of the digits in the number 100!

from python_code.decorators import euler_timer
from math import factorial

@euler_timer(20)
def main():
    print sum([ int(digit) for digit in str(factorial(100)) ])

if __name__ == "__main__":
    main()
