#!/usr/bin/env python

# Find the sum of all the numbers that can be written
# as the sum of fifth powers of their digits.

# n =  d-digits, sum(n) <= d*9^5 = 59049d, n >= 10^(d-1),
# so sum(n) = n implies 10*(9**5 d) >= 10**d,
# ln(10 * 9**5) + ln(d) >= d ln(10), so d <= 6

from python_code.decorators import euler_timer

def sum_of_digits_powers(n, power):
    return sum([ int(dig)**power for dig in str(n) ])

def all_digits_power5():
    result = []
    for i in range(2,999999 + 1):
        if sum_of_digits_powers(i, 5) == i:
            result.append(i)
    return result


@euler_timer(30)
def main():
    ans = all_digits_power5()
    print "%s.\nThe numbers satisfying this property are: %s." % (sum(ans),
        ", ".join([ str(num) for num in ans ]))

if __name__ == "__main__":
    main()
