#!/usr/bin/env python

# Considering natural numbers of the form, a^(b), where a, b < 100, what
# is the maximum digital sum?

import operator

from python_code.decorators import euler_timer
from python_code.functions import apply_to_list

def digit_sum(n):
    return sum([int(dig) for dig in str(n)])

@euler_timer(56)
def main():
    print max([digit_sum(val) for val in apply_to_list(operator.pow, range(1,100))])

if __name__ == "__main__":
    main()
