#!/usr/bin/env python

from python_code.decorators import euler_timer
from python_code.functions import get_data
from python_code.functions import prims_algo

@euler_timer(107)
def main():
    data = [row.split(',') for row in get_data(107).split('\r\n') if row]

    adjacency = {}
    size = len(data)
    network_sum = 0
    # UNDIRECTED
    for node in range(size - 1):
        for dest in range(node + 1, size):
            if data[node][dest] != '-':
                value = int(data[node][dest])
                network_sum += value
                if node in adjacency:
                    adjacency[node].append((dest, value))
                else:
                    adjacency[node] = [(dest, value)]
                if dest in adjacency:
                    adjacency[dest].append((node, value))
                else:
                    adjacency[dest] = [(node, value)]

    _, min_sum = prims_algo(adjacency)

    print network_sum - min_sum

if __name__ == "__main__":
    main()
