#!/usr/bin/env python

from python_code.decorators import euler_timer
from python_code.functions import fill_count

@euler_timer(115)
def main():
    count = 2
    n = 50
    while count <= 10**6:
        n += 1
        count = fill_count(50, n)
    print n

if __name__ == "__main__":
    main()
